name: Push to DockerHub

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Push images to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/angelo-astro:latest

#      - name: Regenerate environments on Aruba
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |
#                    bash /docker/gestionesagre/rigeneraAmbiente.sh
